/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["GetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email and password */
        post: operations["PostAuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout current session */
        post: operations["PostAuthLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user and tenant */
        get: operations["GetAuthMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get csrf token for session */
        get: operations["GetAuthCsrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create customer */
        post: operations["PostCustomers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{customerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get customer by id */
        get: operations["GetCustomersCustomerId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estimates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a draft estimate */
        post: operations["PostEstimates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estimates/{estimateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get estimate by id */
        get: operations["GetEstimatesEstimateId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update estimate fields */
        patch: operations["PatchEstimatesEstimateId"];
        trace?: never;
    };
    "/estimates/{estimateId}/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Convert estimate to job (idempotent) */
        post: operations["PostEstimatesEstimateIdConvert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List scheduled jobs for a monthly calendar range
         * @description Returns jobs where `scheduledDate` is within `[from, to)` (inclusive `from`, exclusive `to`). `userId` and `departmentId` are accepted as filter placeholders but are currently ignored.
         *
         */
        get: operations["GetCalendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get job by id */
        get: operations["GetJobsJobId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update minimal job scheduling fields */
        patch: operations["PatchJobsJobId"];
        trace?: never;
    };
    "/jobs/{jobId}/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a storage record for a job */
        post: operations["PostJobsJobIdStorage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List storage rows for a facility */
        get: operations["GetStorage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/{storageRecordId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get storage record by id */
        get: operations["GetStorageStorageRecordId"];
        /** Replace editable storage record fields */
        put: operations["PutStorageStorageRecordId"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthSessionResponse: {
            user: components["schemas"]["User"];
            tenant: components["schemas"]["Tenant"];
        };
        Tenant: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            fullName: string;
        };
        CreateCustomerRequest: {
            firstName: string;
            lastName: string;
            /** Format: email */
            email?: string;
            phone?: string;
        };
        Customer: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            firstName: string;
            lastName: string;
            /** Format: email */
            email?: string;
            phone?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateEstimateRequest: {
            customerName: string;
            primaryPhone: string;
            secondaryPhone?: string;
            /** Format: email */
            email: string;
            originAddressLine1: string;
            originCity: string;
            originState: string;
            originPostalCode: string;
            destinationAddressLine1: string;
            destinationCity: string;
            destinationState: string;
            destinationPostalCode: string;
            /** Format: date */
            moveDate: string;
            pickupTime?: string;
            leadSource: string;
            moveSize?: string;
            locationType?: string;
            /** Format: int64 */
            estimatedTotalCents?: number;
            /** Format: int64 */
            depositCents?: number;
            notes?: string;
        };
        UpdateEstimateRequest: {
            customerName?: string;
            primaryPhone?: string;
            secondaryPhone?: string;
            /** Format: email */
            email?: string;
            originAddressLine1?: string;
            originCity?: string;
            originState?: string;
            originPostalCode?: string;
            destinationAddressLine1?: string;
            destinationCity?: string;
            destinationState?: string;
            destinationPostalCode?: string;
            /** Format: date */
            moveDate?: string;
            pickupTime?: string;
            leadSource?: string;
            moveSize?: string;
            locationType?: string;
            /** Format: int64 */
            estimatedTotalCents?: number;
            /** Format: int64 */
            depositCents?: number;
            notes?: string;
        };
        Estimate: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            estimateNumber: string;
            /** Format: uuid */
            customerId: string;
            customerName: string;
            primaryPhone: string;
            secondaryPhone?: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            status: "draft" | "converted";
            originAddressLine1: string;
            originCity: string;
            originState: string;
            originPostalCode: string;
            destinationAddressLine1: string;
            destinationCity: string;
            destinationState: string;
            destinationPostalCode: string;
            /** Format: date */
            moveDate: string;
            pickupTime?: string;
            leadSource: string;
            moveSize?: string;
            locationType?: string;
            /** Format: int64 */
            estimatedTotalCents?: number;
            /** Format: int64 */
            depositCents?: number;
            notes?: string;
            /** Format: uuid */
            convertedJobId?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        EstimateResponse: {
            estimate: components["schemas"]["Estimate"];
            requestId: string;
        };
        UpdateJobRequest: {
            /** Format: date */
            scheduledDate?: string;
            pickupTime?: string;
            /** @enum {string} */
            status?: "booked" | "scheduled" | "completed" | "cancelled";
        };
        CalendarJobCard: {
            /** Format: uuid */
            jobId: string;
            jobNumber: string;
            /** Format: date */
            scheduledDate: string;
            pickupTime?: string;
            customerName: string;
            originShort: string;
            destinationShort: string;
            /** @enum {string} */
            status: "booked" | "scheduled" | "completed" | "cancelled";
            hasStorage: boolean;
            /** Format: int64 */
            balanceDueCents: number;
        };
        CalendarResponse: {
            jobs: components["schemas"]["CalendarJobCard"][];
            requestId: string;
        };
        Job: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            jobNumber: string;
            /** Format: uuid */
            customerId: string;
            customerName: string;
            primaryPhone: string;
            /** Format: email */
            email: string;
            /** Format: uuid */
            estimateId?: string;
            /** @enum {string} */
            status: "booked" | "scheduled" | "completed" | "cancelled";
            /** Format: date */
            scheduledDate?: string;
            pickupTime?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        JobResponse: {
            job: components["schemas"]["Job"];
            requestId: string;
        };
        /** @enum {string} */
        StorageStatus: "in_storage" | "sit" | "out";
        CreateStorageRecordRequest: {
            facility: string;
            status?: components["schemas"]["StorageStatus"];
            /** Format: date */
            dateIn?: string;
            /** Format: date */
            dateOut?: string;
            /** Format: date */
            nextBillDate?: string;
            lotNumber?: string;
            locationLabel?: string;
            vaults?: number;
            pads?: number;
            items?: number;
            oversizeItems?: number;
            volume?: number;
            /** Format: int64 */
            monthlyRateCents?: number;
            /** Format: int64 */
            storageBalanceCents?: number;
            /** Format: int64 */
            moveBalanceCents?: number;
            /** Format: date-time */
            lastPaymentAt?: string;
            notes?: string;
        };
        UpdateStorageRecordRequest: {
            facility: string;
            status: components["schemas"]["StorageStatus"];
            /** Format: date */
            dateIn?: string;
            /** Format: date */
            dateOut?: string;
            /** Format: date */
            nextBillDate?: string;
            lotNumber?: string;
            locationLabel?: string;
            vaults: number;
            pads: number;
            items: number;
            oversizeItems: number;
            volume: number;
            /** Format: int64 */
            monthlyRateCents?: number;
            /** Format: int64 */
            storageBalanceCents: number;
            /** Format: int64 */
            moveBalanceCents: number;
            /** Format: date-time */
            lastPaymentAt?: string;
            notes?: string;
        };
        StorageListItem: {
            /** Format: uuid */
            storageRecordId?: string | null;
            /** Format: uuid */
            jobId: string;
            jobNumber: string;
            customerName: string;
            moveType?: string | null;
            fromShort: string;
            toShort: string;
            /** @enum {string|null} */
            status?: "in_storage" | "sit" | "out" | null;
            /** Format: date */
            dateIn?: string | null;
            /** Format: date */
            dateOut?: string | null;
            /** Format: date */
            nextBillDate?: string | null;
            lotNumber?: string | null;
            locationLabel?: string | null;
            vaults: number;
            pads: number;
            items: number;
            oversizeItems: number;
            volume: number;
            /** Format: int64 */
            monthlyRateCents?: number | null;
            /** Format: int64 */
            storageBalanceCents: number;
            /** Format: int64 */
            moveBalanceCents: number;
            facility: string;
        };
        StorageListResponse: {
            items: components["schemas"]["StorageListItem"][];
            nextCursor?: string | null;
            requestId: string;
        };
        StorageRecord: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            jobId: string;
            jobNumber: string;
            customerName: string;
            moveType?: string;
            fromShort: string;
            toShort: string;
            facility: string;
            status: components["schemas"]["StorageStatus"];
            /** Format: date */
            dateIn?: string;
            /** Format: date */
            dateOut?: string;
            /** Format: date */
            nextBillDate?: string;
            lotNumber?: string;
            locationLabel?: string;
            vaults: number;
            pads: number;
            items: number;
            oversizeItems: number;
            volume: number;
            /** Format: int64 */
            monthlyRateCents?: number;
            /** Format: int64 */
            storageBalanceCents: number;
            /** Format: int64 */
            moveBalanceCents: number;
            /** Format: date-time */
            lastPaymentAt?: string;
            notes?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        StorageRecordResponse: {
            storage: components["schemas"]["StorageRecord"];
            requestId: string;
        };
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                details?: unknown;
            };
            requestId: string;
        };
    };
    responses: {
        /** @description Standard API error */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
        };
    };
    PostAuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    PostAuthLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    GetAuthMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session principal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    GetAuthCsrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF token response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        csrfToken: string;
                    };
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    PostCustomers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomerRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    GetCustomersCustomerId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    PostEstimates: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEstimateRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay returned existing estimate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateResponse"];
                };
            };
            /** @description Draft estimate created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    GetEstimatesEstimateId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                estimateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estimate details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    PatchEstimatesEstimateId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                estimateId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEstimateRequest"];
            };
        };
        responses: {
            /** @description Estimate updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    PostEstimatesEstimateIdConvert: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                estimateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Idempotent replay returned existing job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Job created from estimate */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    GetCalendar: {
        parameters: {
            query: {
                from: string;
                to: string;
                phase?: "booked" | "scheduled" | "completed" | "cancelled";
                jobType?: "local" | "long_distance" | "other";
                /** @description Placeholder filter; accepted but currently ignored. */
                userId?: string;
                /** @description Placeholder filter; accepted but currently ignored. */
                departmentId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Calendar jobs in range */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    GetJobsJobId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    PatchJobsJobId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateJobRequest"];
            };
        };
        responses: {
            /** @description Job updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    PostJobsJobIdStorage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStorageRecordRequest"];
            };
        };
        responses: {
            /** @description Storage record created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageRecordResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    GetStorage: {
        parameters: {
            query: {
                facility: string;
                q?: string;
                status?: components["schemas"]["StorageStatus"];
                hasDateOut?: boolean;
                balanceDue?: boolean;
                pastDueDays?: number;
                hasContainers?: boolean;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Storage rows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageListResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    GetStorageStorageRecordId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storageRecordId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Storage record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageRecordResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    PutStorageStorageRecordId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storageRecordId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStorageRecordRequest"];
            };
        };
        responses: {
            /** @description Storage record updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageRecordResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
}
