// Generated by openapi-typescript. DO NOT EDIT.

export type LoginRequest = {
  email: string;
  password: string;
};

export type Tenant = {
  id: string;
  slug: string;
  name: string;
};

export type User = {
  id: string;
  email: string;
  fullName: string;
};

export type AuthSessionResponse = {
  user: User;
  tenant: Tenant;
};

export type CreateCustomerRequest = {
  firstName: string;
  lastName: string;
  email?: string;
  phone?: string;
};

export type Customer = {
  id: string;
  tenantId: string;
  firstName: string;
  lastName: string;
  email?: string;
  phone?: string;
  createdAt: string;
  updatedAt: string;
};

export type ErrorEnvelope = {
  error: {
    code: string;
    message: string;
    details?: unknown;
  };
  requestId: string;
};
